#!/usr/bin/env ruby
require 'mister_bin'

exitcode =  MisterBin::Runner.run __FILE__, ARGV,
  header: "This is a sample header.",
  footer: "This is a sample footer.\nUse --help for each command to get more information"

exit exitcode