require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.0

# The examples spec is special, it is allowed to be longer
RSpec/ExampleLength:
  Exclude:
    - 'spec/mister_bin/xamples_spec.rb'

# The examples spec is special, it is allowed to use `it 'works'`
RSpec/ExampleWording:
  Exclude:
    - 'spec/mister_bin/xamples_spec.rb'
